version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/entrypoint"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"