// Code generated by mockery v2.53.3. DO NOT EDIT.

package sriovnet

import mock "github.com/stretchr/testify/mock"

// Lib is an autogenerated mock type for the Lib type
type Lib struct {
	mock.Mock
}

type Lib_Expecter struct {
	mock *mock.Mock
}

func (_m *Lib) EXPECT() *Lib_Expecter {
	return &Lib_Expecter{mock: &_m.Mock}
}

// GetPciFromNetDevice provides a mock function with given fields: name
func (_m *Lib) GetPciFromNetDevice(name string) (string, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetPciFromNetDevice")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lib_GetPciFromNetDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPciFromNetDevice'
type Lib_GetPciFromNetDevice_Call struct {
	*mock.Call
}

// GetPciFromNetDevice is a helper method to define mock.On call
//   - name string
func (_e *Lib_Expecter) GetPciFromNetDevice(name interface{}) *Lib_GetPciFromNetDevice_Call {
	return &Lib_GetPciFromNetDevice_Call{Call: _e.mock.On("GetPciFromNetDevice", name)}
}

func (_c *Lib_GetPciFromNetDevice_Call) Run(run func(name string)) *Lib_GetPciFromNetDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Lib_GetPciFromNetDevice_Call) Return(_a0 string, _a1 error) *Lib_GetPciFromNetDevice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Lib_GetPciFromNetDevice_Call) RunAndReturn(run func(string) (string, error)) *Lib_GetPciFromNetDevice_Call {
	_c.Call.Return(run)
	return _c
}

// NewLib creates a new instance of Lib. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLib(t interface {
	mock.TestingT
	Cleanup(func())
}) *Lib {
	mock := &Lib{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
