version: "2"
run:
  timeout: 10m
  modules-download-mode: readonly
  tests: false
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - fatcontext
    - funlen
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - tagalign
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    funlen:
      lines: 120
      statements: 55
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - appendAssign
    gocyclo:
      min-complexity: 30
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      rules:
        - name: package-comments
          severity: warning
          disabled: true
          exclude:
            - ""
        - name: import-shadowing
          severity: warning
          disabled: false
          exclude:
            - ""
        - name: exported
          arguments:
            - checkPrivateReceivers
            - checkPublicInterface
          severity: warning
          disabled: false
          exclude:
            - ""
    staticcheck:
      checks:
        - all
        - -ST1000
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/ginkgo/v2/extensions/table
        - github.com/onsi/gomega
        - github.com/onsi/gomega/gstruct
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Mellanox/doca-driver-build
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
