with-expecter: True
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  github.com/Mellanox/doca-driver-build/entrypoint/internal:
    config:
      recursive: True
