// Code generated by mockery v2.46.3. DO NOT EDIT.

package driver

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

type Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *Interface) EXPECT() *Interface_Expecter {
	return &Interface_Expecter{mock: &_m.Mock}
}

// Build provides a mock function with given fields: ctx
func (_m *Interface) Build(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Interface_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type Interface_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Interface_Expecter) Build(ctx interface{}) *Interface_Build_Call {
	return &Interface_Build_Call{Call: _e.mock.On("Build", ctx)}
}

func (_c *Interface_Build_Call) Run(run func(ctx context.Context)) *Interface_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Interface_Build_Call) Return(_a0 error) *Interface_Build_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_Build_Call) RunAndReturn(run func(context.Context) error) *Interface_Build_Call {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function with given fields: ctx
func (_m *Interface) Clear(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Interface_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type Interface_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Interface_Expecter) Clear(ctx interface{}) *Interface_Clear_Call {
	return &Interface_Clear_Call{Call: _e.mock.On("Clear", ctx)}
}

func (_c *Interface_Clear_Call) Run(run func(ctx context.Context)) *Interface_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Interface_Clear_Call) Return(_a0 error) *Interface_Clear_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_Clear_Call) RunAndReturn(run func(context.Context) error) *Interface_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: ctx
func (_m *Interface) Load(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Interface_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Interface_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Interface_Expecter) Load(ctx interface{}) *Interface_Load_Call {
	return &Interface_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *Interface_Load_Call) Run(run func(ctx context.Context)) *Interface_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Interface_Load_Call) Return(_a0 bool, _a1 error) *Interface_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Interface_Load_Call) RunAndReturn(run func(context.Context) (bool, error)) *Interface_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function with given fields: ctx
func (_m *Interface) Prepare(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Interface_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type Interface_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Interface_Expecter) Prepare(ctx interface{}) *Interface_Prepare_Call {
	return &Interface_Prepare_Call{Call: _e.mock.On("Prepare", ctx)}
}

func (_c *Interface_Prepare_Call) Run(run func(ctx context.Context)) *Interface_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Interface_Prepare_Call) Return(_a0 error) *Interface_Prepare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_Prepare_Call) RunAndReturn(run func(context.Context) error) *Interface_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// Unload provides a mock function with given fields: ctx
func (_m *Interface) Unload(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Unload")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Interface_Unload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unload'
type Interface_Unload_Call struct {
	*mock.Call
}

// Unload is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Interface_Expecter) Unload(ctx interface{}) *Interface_Unload_Call {
	return &Interface_Unload_Call{Call: _e.mock.On("Unload", ctx)}
}

func (_c *Interface_Unload_Call) Run(run func(ctx context.Context)) *Interface_Unload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Interface_Unload_Call) Return(_a0 bool, _a1 error) *Interface_Unload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Interface_Unload_Call) RunAndReturn(run func(context.Context) (bool, error)) *Interface_Unload_Call {
	_c.Call.Return(run)
	return _c
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
