// Code generated by mockery v2.46.3. DO NOT EDIT.

package netconfig

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

type Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *Interface) EXPECT() *Interface_Expecter {
	return &Interface_Expecter{mock: &_m.Mock}
}

// Restore provides a mock function with given fields: ctx
func (_m *Interface) Restore(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Interface_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type Interface_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Interface_Expecter) Restore(ctx interface{}) *Interface_Restore_Call {
	return &Interface_Restore_Call{Call: _e.mock.On("Restore", ctx)}
}

func (_c *Interface_Restore_Call) Run(run func(ctx context.Context)) *Interface_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Interface_Restore_Call) Return(_a0 error) *Interface_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_Restore_Call) RunAndReturn(run func(context.Context) error) *Interface_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx
func (_m *Interface) Save(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Interface_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Interface_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Interface_Expecter) Save(ctx interface{}) *Interface_Save_Call {
	return &Interface_Save_Call{Call: _e.mock.On("Save", ctx)}
}

func (_c *Interface_Save_Call) Run(run func(ctx context.Context)) *Interface_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Interface_Save_Call) Return(_a0 error) *Interface_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_Save_Call) RunAndReturn(run func(context.Context) error) *Interface_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
