pipeline {
  agent {
    kubernetes {
      yamlFile "ci/agent_pod.yaml"
    }
  }

  options {
    timestamps()
    ansiColor("xterm")
  }

  environment {
    DOCKER_REGISTRY = "nvcr.io/nvstaging/mellanox"
    DOCKER_IMAGE_NAME = "doca-driver"
  }

  stages {
    stage("Init") {
      steps {
        sh("""
          echo "FROM alpine" >> Dockerfile
          echo "RUN echo mock > main.txt" >> Dockerfile
        """)
        container("dind") {
          sh("until nc -vz localhost 2375; do sleep 2; done")
        }
      }
    }

    stage("Precompile build matrices") {
      // ubuntu
      matrix {
        axes {
          axis {
            name "FLAVOR"
            values "generic", "aws", "azure", "oracle", "nvidia"
          }
          axis {
            name "VERSION"
            values "24.04", "22.04"
          }
          axis {
            name "ARCHITECTURE"
            values "linux/amd64", "linux/arm64"
          }
        }
        stages {

          stage("Init") {
            steps {
              sh("""
                echo DOCKER_TAG shall be ubuntu$VERSION-$FLAVOR-$ARCHITECTURE
              """)
            }
          }

          stage("Kaniko") {
            steps {
              container("kaniko") {
                sh("""
                  /kaniko/executor version
                """)
              }
            }
          }

          stage("Docker") {
            steps {
              container("dind") {
                sh("""
                  docker info
                """)
              }
            }
          }

        }
      }

      // rhel & rhcos
      // matrix {
      //   axes {
      //     axis {
      //       name "OS"
      //       values "rhel", "rhcos"
      //     }
      //     axis {
      //       name "VERSION"
      //       values "9.4", "9.3", "9.2", "8.10", "8.9", "8.8", "4.16"
      //     }
      //     axis {
      //       name "ARCHITECTURE"
      //       values "linux/amd64", "linux/arm64"
      //     }
      //     excludes {
      //       exclude {
      //         axis {
      //           name "OS"
      //           values "rhel"
      //         }
      //         axis {
      //           name "VERSION"
      //           values "4.16"
      //         }
      //       }
      //       exclude {
      //         axis {
      //           name "OS"
      //           values "rhel"
      //         }
      //         axis {
      //           name "ARCHITECTURE"
      //           values "linux/arm64"
      //         }
      //       }
      //     }
      //   }
      //   environment {
      //     RH_MAJOR_VERSION_TO_USE_FOR_LATEST_KERNEL_LOOKUPS = "9"
      //   }
      //   stages {

      //     stage("Init") {
      //       steps {
      //         sh("""
      //           echo DOCKER_TAG shall be $OS$VERSION-$ARCHITECTURE
      //         """)
      //       }
      //     }

      //     stage("Kaniko") {
      //       steps {
      //         container("kaniko") {
      //           sh("""
      //             /kaniko/executor version
      //           """)
      //         }
      //       }
      //     }

      //     stage("Docker") {
      //       steps {
      //         container("dind") {
      //           sh("""
      //             docker info
      //           """)
      //         }
      //       }
      //     }

      //   }
      // }

    }
  }
}

