// Code generated by mockery v2.46.3. DO NOT EDIT.

package wrappers

import (
	fs "io/fs"
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// OSWrapper is an autogenerated mock type for the OSWrapper type
type OSWrapper struct {
	mock.Mock
}

type OSWrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *OSWrapper) EXPECT() *OSWrapper_Expecter {
	return &OSWrapper_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: name
func (_m *OSWrapper) Create(name string) (*os.File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *os.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OSWrapper_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OSWrapper_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
func (_e *OSWrapper_Expecter) Create(name interface{}) *OSWrapper_Create_Call {
	return &OSWrapper_Create_Call{Call: _e.mock.On("Create", name)}
}

func (_c *OSWrapper_Create_Call) Run(run func(name string)) *OSWrapper_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OSWrapper_Create_Call) Return(_a0 *os.File, _a1 error) *OSWrapper_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OSWrapper_Create_Call) RunAndReturn(run func(string) (*os.File, error)) *OSWrapper_Create_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function with given fields: path, perm
func (_m *OSWrapper) MkdirAll(path string, perm fs.FileMode) error {
	ret := _m.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = rf(path, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OSWrapper_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type OSWrapper_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm fs.FileMode
func (_e *OSWrapper_Expecter) MkdirAll(path interface{}, perm interface{}) *OSWrapper_MkdirAll_Call {
	return &OSWrapper_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *OSWrapper_MkdirAll_Call) Run(run func(path string, perm fs.FileMode)) *OSWrapper_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(fs.FileMode))
	})
	return _c
}

func (_c *OSWrapper_MkdirAll_Call) Return(_a0 error) *OSWrapper_MkdirAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OSWrapper_MkdirAll_Call) RunAndReturn(run func(string, fs.FileMode) error) *OSWrapper_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function with given fields: name
func (_m *OSWrapper) ReadDir(name string) ([]fs.DirEntry, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OSWrapper_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type OSWrapper_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *OSWrapper_Expecter) ReadDir(name interface{}) *OSWrapper_ReadDir_Call {
	return &OSWrapper_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *OSWrapper_ReadDir_Call) Run(run func(name string)) *OSWrapper_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OSWrapper_ReadDir_Call) Return(_a0 []fs.DirEntry, _a1 error) *OSWrapper_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OSWrapper_ReadDir_Call) RunAndReturn(run func(string) ([]fs.DirEntry, error)) *OSWrapper_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: name
func (_m *OSWrapper) ReadFile(name string) ([]byte, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OSWrapper_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type OSWrapper_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name string
func (_e *OSWrapper_Expecter) ReadFile(name interface{}) *OSWrapper_ReadFile_Call {
	return &OSWrapper_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *OSWrapper_ReadFile_Call) Run(run func(name string)) *OSWrapper_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OSWrapper_ReadFile_Call) Return(_a0 []byte, _a1 error) *OSWrapper_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OSWrapper_ReadFile_Call) RunAndReturn(run func(string) ([]byte, error)) *OSWrapper_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function with given fields: path
func (_m *OSWrapper) RemoveAll(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OSWrapper_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type OSWrapper_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *OSWrapper_Expecter) RemoveAll(path interface{}) *OSWrapper_RemoveAll_Call {
	return &OSWrapper_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *OSWrapper_RemoveAll_Call) Run(run func(path string)) *OSWrapper_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OSWrapper_RemoveAll_Call) Return(_a0 error) *OSWrapper_RemoveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OSWrapper_RemoveAll_Call) RunAndReturn(run func(string) error) *OSWrapper_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: name
func (_m *OSWrapper) Stat(name string) (fs.FileInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OSWrapper_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type OSWrapper_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *OSWrapper_Expecter) Stat(name interface{}) *OSWrapper_Stat_Call {
	return &OSWrapper_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *OSWrapper_Stat_Call) Run(run func(name string)) *OSWrapper_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OSWrapper_Stat_Call) Return(_a0 fs.FileInfo, _a1 error) *OSWrapper_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OSWrapper_Stat_Call) RunAndReturn(run func(string) (fs.FileInfo, error)) *OSWrapper_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function with given fields: name, data, perm
func (_m *OSWrapper) WriteFile(name string, data []byte, perm fs.FileMode) error {
	ret := _m.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = rf(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OSWrapper_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type OSWrapper_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name string
//   - data []byte
//   - perm fs.FileMode
func (_e *OSWrapper_Expecter) WriteFile(name interface{}, data interface{}, perm interface{}) *OSWrapper_WriteFile_Call {
	return &OSWrapper_WriteFile_Call{Call: _e.mock.On("WriteFile", name, data, perm)}
}

func (_c *OSWrapper_WriteFile_Call) Run(run func(name string, data []byte, perm fs.FileMode)) *OSWrapper_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(fs.FileMode))
	})
	return _c
}

func (_c *OSWrapper_WriteFile_Call) Return(_a0 error) *OSWrapper_WriteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OSWrapper_WriteFile_Call) RunAndReturn(run func(string, []byte, fs.FileMode) error) *OSWrapper_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewOSWrapper creates a new instance of OSWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOSWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *OSWrapper {
	mock := &OSWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
