// Code generated by mockery v2.46.3. DO NOT EDIT.

package ready

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

type Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *Interface) EXPECT() *Interface_Expecter {
	return &Interface_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with given fields: ctx
func (_m *Interface) Clear(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Interface_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type Interface_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Interface_Expecter) Clear(ctx interface{}) *Interface_Clear_Call {
	return &Interface_Clear_Call{Call: _e.mock.On("Clear", ctx)}
}

func (_c *Interface_Clear_Call) Run(run func(ctx context.Context)) *Interface_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Interface_Clear_Call) Return(_a0 error) *Interface_Clear_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_Clear_Call) RunAndReturn(run func(context.Context) error) *Interface_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx
func (_m *Interface) Set(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Interface_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Interface_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Interface_Expecter) Set(ctx interface{}) *Interface_Set_Call {
	return &Interface_Set_Call{Call: _e.mock.On("Set", ctx)}
}

func (_c *Interface_Set_Call) Run(run func(ctx context.Context)) *Interface_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Interface_Set_Call) Return(_a0 error) *Interface_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_Set_Call) RunAndReturn(run func(context.Context) error) *Interface_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
